### ISSUE TITLE
Is there a way to load multiple configuration files ?

### ISSUE THREAD

**Issue by yvz5** [unitycontainer/configuration#10]
Hi there, I was wondering if there is a way to load multiple config files and register them to the container instead of returning an `IUnityContainer` ?

**Comment by ENikS** [comment]
I believe there is a way to do it. Look at the [LoadConfiguration](https://github.com/unitycontainer/configuration/blob/master/src/Extensions/UnityContainerConfigurationExtensions.cs) extension method for the example.
