### ISSUE TITLE
I run the wpf sample project,when update the nuget package "Unity.Container" and "Unity.Abstractions",something error

### ISSUE THREAD

**Issue by indexlang** [unitycontainer/configuration#14]
update the nuget package "Unity.Container" from 5.8.11 to 5.9.4 and "Unity.Abstractions" from 3.3.1 to 4.0.3,same error happen :
System.IO.FileLoadException
  HResult=0x80131040
  Message=cannot load “Unity.Abstractions, Version=3.3.1.0, Culture=neutral, PublicKeyToken=6d32ff45e0ccc69f” or it's depends
  Source=Prism.Unity.Wpf
  StackTrace:
    Prism.Unity.PrismApplication.CreateContainerExtension()
    Prism.PrismApplicationBase.Initialize()
    Prism.PrismApplicationBase.InitializeInternal()
    Prism.PrismApplicationBase.OnStartup(StartupEventArgs e)
    System.Windows.Application.<.ctor>b__1_0(Object unused)
    System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
    System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
    System.Windows.Threading.DispatcherOperation.InvokeImpl()
    System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
    System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
    System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
    MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
    System.Windows.Threading.DispatcherOperation.Invoke()
    System.Windows.Threading.Dispatcher.ProcessQueue()
    System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
    MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
    MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
    System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
    System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
    MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
    MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
    System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
    System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
    System.Windows.Application.RunDispatcher(Object ignore)
    System.Windows.Application.RunInternal(Window window)
    System.Windows.Application.Run(Window window)
    System.Windows.Application.Run()
    Regions.App.Main() 在 D:\GITRepo\Prism-Samples-Wpf\02-Regions\Regions\obj\Debug\App.g.cs line 57

**Comment by ENikS** [comment]
The error is clearly states it is looking for previous version of Unity. Old and new packaged are not compatible so you can not binding redirect one to another.

You will have to wait for Prism team to update their references to the new package.
