### ISSUE TITLE
5.9.2 version

### ISSUE THREAD

**Issue by Kantuz001** [unitycontainer/configuration#15]
Hi, i have Unity.Configuration 5.9.2 version which one depends on Unity.Container 5.9.5 version which one depends on Unity.Abstractions 4.0.3
so Unity.Configuration 5.9.2 -> Unity.Container 5.9.5 -> Unity.Abstractions 4.0.3

Also i have Unity.Abstractions 4.1.0

So that i get runtime error, Unity.Abstractions 4.0.3 cannot be found

**Comment by ENikS** [comment]
Why would you upgrade one but not the other?
