### ISSUE TITLE
Namespace of extension methods

### ISSUE THREAD

**Issue by florianbaer** [unitycontainer/configuration#21]
Is there a reason, why multiple extensions (find them here: `configuration/src/Extensions`) are still in the namespace `Microsoft.Practices.Unity.Configuration.ConfigurationHelpers`?

If i want to load the unity configuration with the extension `container.LoadConfiguration(unitySection);`, i still have to include the namespace `Microsoft.Practices.Unity.Configuration;`.

Is this by intention or just not migrated yet?

Thanks for the help

**Comment by ENikS** [comment]
I is not migrated yet. Someone needs to take time and do it.
