### ISSUE TITLE
Breaking change

### ISSUE THREAD

**Issue by MrSkiv** [unitycontainer/configuration#23]
When in config file is defined type with multiple methods - only first is executed. Till version 5.8 everything worked ok, after 5.9 - only first. Same is 5.10 and 5.11.
 Example bellow.

    class Program
    {
        static void Main(string[] args)
        {
            IUnityContainer container = new UnityContainer();
            container.LoadConfiguration();

            var t = container.Resolve<MyClassCollection>();
            Console.WriteLine(t.MyItems.Count);

        }
    }

    public class MyClassCollection
    {
        public IReadOnlyList<IMy> MyItems { get; set; } = new List<IMy>();

        public void Add(IMy pParam)
        {
            ((List<IMy>)MyItems).Add(pParam);
        }
    }

    public class MyClass : IMy
    {

    }

    public interface IMy
    {

    }

Config is:
      
<unity xmlns="http://schemas.microsoft.com/practices/2010/unity">
    <assembly name="UnityBug" />

    <container>
      <register type="UnityBug.IMy" mapTo="UnityBug.MyClass" name="inst1"/>
      <register type="UnityBug.IMy" mapTo="UnityBug.MyClass" name="inst2"/>
      <register type="UnityBug.IMy" mapTo="UnityBug.MyClass" name="inst3"/>
      <register type="UnityBug.IMy" mapTo="UnityBug.MyClass" name="inst4"/>

      <register type="UnityBug.MyClassCollection">
        <method name="Add">
          <param name="pParam" dependencyName="inst1"/>
        </method>
        <method name="Add">
          <param name="pParam" dependencyName="inst2"/>
        </method>
        <method name="Add">
          <param name="pParam" dependencyName="inst3"/>
        </method>
        <method name="Add">
          <param name="pParam" dependencyName="inst4"/>
        </method>
      </register>
    </container>
    </unity>

Sample project:
[UnityBug.zip](https://github.com/unitycontainer/configuration/files/3569191/UnityBug.zip)

**Comment by MrSkiv** [comment]
Is someone reading these issues or project is abandoned?

**Comment by ENikS** [comment]
I am reading it but unable to work on the project at the moment

**Comment by ENikS** [comment]
The container does not support calling the same method multiple times. It only calls distinct methods.
You would have either create multiple methods or change method's signature to accommodate every case.
