### ISSUE TITLE
Upgrade from 5.0.0 to 5.11.1,there's a problem

### ISSUE THREAD

**Issue by jiangxiangji** [unitycontainer/configuration#24]
Upgrade to 5.11.1,Service of OptionalTest.Name is null(required Test)
Work correctly for 5.0.0

`
        <register type="A1" name="TestA1">
          <property name="Name" type="string" value="Test"></property>
        </register>
`
`
        <register type="OptionalTest" name="OptionalTest">
          <property name="Service">
            <optional name="TestA1" type="A1" />
          </property>
        </register>
`
`
    public class A1: A{}
`
`
    public class OptionalTest
    {
        public A Service { get; set; }
    }
`

**Comment by ENikS** [comment]
Fixed in 5.11.2
