### ISSUE TITLE
Unity.Configuration

### ISSUE THREAD

**Issue by MatzeG** [unitycontainer/configuration#3]
The Package Unity.Configuration did not contain any 4.0 lib. 
Unity.Configuration 5.0.7

This package is compatible with .NET 4.0, 4.5, and 4.7 frameworks.
=>  Dependencies
.NETFramework 4.5
Unity.Abstractions (>= 2.3.0)

.NETFramework 4.7
Unity.Abstractions (>= 2.3.0)

**Comment by ENikS** [comment]
Yes, my mistake. I've updated description

**Comment by ENikS** [comment]
Are you pointing out discrepancy or looking for NET 4.0 implementation?

**Comment by ENikS** [comment]
Fixed
