### ISSUE TITLE
net core

### ISSUE THREAD

**Issue by ARamilK** [unitycontainer/configuration#5]
Could you please provide an information on release unitycontainer/configuration under core 2.0?
Do you have any plans to port it?
If so, could you provide the estimated release date?

**Comment by ENikS** [comment]
I am working on v6 engine and will be busy for a while. I understand mister @Chavoshi is willing to help with the effort. It has been discussed [here](https://github.com/unitycontainer/unity/issues/198#issuecomment-375962519)

**Comment by michaelp** [comment]
@ENikS & @Chavoshi  - Thank you for your work. (I noticed your last commits). When do you think the nuget package is going to be published?

**Comment by ENikS** [comment]
It is deployed
