### ISSUE TITLE
Configuring Liftetime in registration causes object to immediately Dispose

### ISSUE THREAD

**Issue by dekenless** [unitycontainer/configuration#6]
I am migrating from 4.0.1 (this all worked in that version) and have something like this (LogInfo implements Dispose):

```
 <register type="ILogInfo" mapTo="Foo.LogInfo, Foo.Logging">
      <lifetime type="singleton" />
    </register>

```
```
var foo = MainContainer.Resolve<ILogInfo>(); 
MainContainer.RegisterInstance<ILogInfo>(foo);
```

When I register the instance, Dispose is immediately called on foo.

Now, if I change the registration to:
```
 <register type="ILogInfo" mapTo="Foo.LogInfo, Foo.Logging">
        </register>
```

And do this, it works:

```
var foo = MainContainer.Resolve<ILogInfo>(); 
MainContainer.RegisterInstance<ILogInfo>(foo, new .SingletonLifetimeManager());
```

**Comment by ENikS** [comment]
What is your question?

**Comment by dekenless** [comment]
No question, pointing out there is a problem when configuring via a config file. Calling RegisterInstance should not cause Dispose to be called on the class that is being registered.

**Comment by dekenless** [comment]
Here is a sample solution demonstrating the issue.
[sample.zip](https://github.com/unitycontainer/configuration/files/1904218/sample.zip)

**Comment by ENikS** [comment]
Thank you. Perhaps you could fix it as well? I would be happy to merge a PR. 
I am a bit indisposed at the moment and it might take a while before I could get to this...

**Comment by dekenless** [comment]
I checked and it was working prior to release 5.7

**Comment by ENikS** [comment]
When you load your configuration:
```
 <register type="ILogInfo" mapTo="Foo.LogInfo, Foo.Logging">
      <lifetime type="singleton" />
    </register>
```
Unity creates singleton registration for type `ILogInfo`. When you execute following two lines
```C#
var foo = MainContainer.Resolve<ILogInfo>(); 
MainContainer.RegisterInstance<ILogInfo>(foo);
```
unity resolves instance in first line and creates new instance registration for the same type `ILogInfo` in the second. 

While doing it, Unity [checks if old instance is `IDisposable`](https://github.com/unitycontainer/container/blob/da2c9f18051863ac1f0de67b1606d28b38afd3b5/src/UnityContainer.IUnityContainer.cs#L122-L129) and if yes, disposes it.
So, to make long story short, remove this line and everything should work: ``MainContainer.RegisterInstance<ILogInfo>(foo);``
