### ISSUE TITLE
One type registered as more different services like autofac

### ISSUE THREAD

**Issue by jiangxiangji** [unitycontainer/configuration#9]
One type registered as more different services is required.
xml configuration of  autofac like this:
`  <components name="Operation">
        <type>Autofac.Example.Calculator.Addition.Add, Autofac.Example.Calculator.Addition</type>
        <services name="Operation" type="Autofac.Example.Calculator.Api.IOperation" />
        <services name="AddOperation" type="Autofac.Example.Calculator.Api.IAddOperation" />
    </components>`

**Comment by ENikS** [comment]
It is done by registering a type with proper lifetime and then registering different interfaces for the type:
```
RegisterType<MyType>(new ..Lifetime);
RegisterType<IMyType1, MyType>();
RegisterType<IMyType2, MyType>();
RegisterType<IMyType3, MyType>();
```

**Comment by ENikS** [comment]
Added [new method](https://github.com/unitycontainer/experimental/issues/42) to do just that.
